### PR TITLE
Replace calls to GetShallowClone 

### LINKED ISSUE #463: Robot_Toolkit: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #463

 

 ### Test files

No functional change.

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: Robot_Adapter/CRUD/Create/Elements/FEMeshes.cs [hunk 1]
```diff
@@ -104,7 +105,7 @@ private bool CreateCollection(IEnumerable<FEMesh> fEMeshes)
                     if (!createNodesSuccess)
                         continue;
 
-                    FEMeshFace clone = fMeshFace.GetShallowClone() as FEMeshFace;
+                    FEMeshFace clone = fMeshFace.ShallowClone() as FEMeshFace;
```
Comment (FraserGreenroyd) [inline Robot_Adapter/CRUD/Create/Elements/FEMeshes.cs:108]:
```suggestion
                    FEMeshFace clone = fMeshFace.ShallowClone();
```

File: Robot_Adapter/Convert/FromRobot/Elements/Bar.cs [hunk 2]
```diff
@@ -100,7 +101,7 @@ public static partial class Convert
                         if (bhomSections.TryGetValue(secName, out secProp))
                         {
                             //Construct and store a copy of the section, with new material
-                            secProp = secProp.GetShallowClone(true) as ISectionProperty;
+                            secProp = secProp.ShallowClone(true) as ISectionProperty;
```
Comment (FraserGreenroyd) [inline Robot_Adapter/Convert/FromRobot/Elements/Bar.cs:104]:
```suggestion
                            secProp = secProp.ShallowClone(true);
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed only.
