### PR TITLE
Null checks when reading bars and avoid pulling of 'Super bars'

### LINKED ISSUE #401: Robot_Toolkit: Read Bar crashes if a nan-bar exists in the model
#### Description:

When a model contains an NaN bar, that is a bar without any nodes set, the read crashes out. Sufficient protection needs to be put in place to make sure this does not happen.

#### Steps to reproduce:

Pull bars from provided testfile

#### Expected behaviour:

For NaN bar to still come out, without anything set, and for nothing to crash.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/Ev4xpwQvlFtAhZEA37LejXwBb2DKOJaoc81oQbczrqLQDQ?e=99YXcI

### LINKED ISSUE #402: Robot_Toolkit: SuperBars should not be pulled when pulling bars
#### Description:

Currently when pulling bars from Robot, both the single Bars as well as the bars made up of multiple elements are returned.

As an initial step, only the single bars should be returned, and a warning raised for the bars containing more than one element.

Long term, those "SuperBars" should be handled by a separate BHoM class.

#### Steps to reproduce:

Pull the bars in the example model.

#### Expected behaviour:

For only single bars to be returned, and for a warning to be raised if the model contains "SuperBars"

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/Ev4xpwQvlFtAhZEA37LejXwBb2DKOJaoc81oQbczrqLQDQ?e=99YXcI

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #401 
Closes #402 

 

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Ev4xpwQvlFtAhZEA37LejXwBb2DKOJaoc81oQbczrqLQDQ?e=JYEN2h

 ### Changelog

- Add null checks for nodes before evaluating if a bar is vertical
- Only pull single segment bars, and raise warning for SuperBars

 ### Additional comments

### CODE REVIEW

File: Robot_Adapter/CRUD/Read/Elements/Bars.cs [hunk 1]
```diff
@@ -112,6 +126,14 @@ private List<Bar> ReadBars(IList ids = null)
 
         /***************************************************/
 
+
+        private void SuperBarWarning()
+        {
+            Engine.Reflection.Compute.RecordWarning("Model contains 'Super Bars' which are not extracted. Reading Bars only extracts the idividual bar segments.");
```
Comment (kThorsager) [inline Robot_Adapter/CRUD/Read/Elements/Bars.cs:132]:
```suggestion
            Engine.Reflection.Compute.RecordWarning("Model contains 'Super Bars' which are not extracted. Reading Bars only extracts the individual bar segments.");
```
