### PR TITLE
Compliance Update and Enable Update Panels

### LINKED ISSUE #184: Robot_Toolkit: Legacy code cleanup
Some minor tidy up of commented code that should not change anything.

### LINKED ISSUE #249: Robot_Toolkit: Change Update method for node constraints
#### Description:

The update method for node constraints is currently calling the create method. This is working, but is very slow. The labels just need to get updated instead, which should improve the performance.

### LINKED ISSUE #250: Robot_Toolkit: Review all update methods
#### Description:

In light of https://github.com/BHoM/Robot_Toolkit/issues/249, all update methods for labels in the Robot toolkit should be reviewed to ensure they are updating the labels rather than re-creating them. From testing on `Constraint6DOF` this could lead to a massive speed improvement.

### LINKED ISSUE #301: Robot_Toolkit: Cleanup of unused files
#### Broken rules:

Found by @kThorsager here https://github.com/BHoM/Robot_Toolkit/pull/293#pullrequestreview-347853243

There are a few enums that are not used anywhere, these should be removed.

#### Suggestions to restore compliance:

Remove unused code

### LINKED ISSUE #308: Robot_Toolkit: Enable Update Only Methods
#### Description:

Will see how much effort this takes to update multiple object methods, but primary need is currently panels. 

@pawelbaran , @alelom , @IsakNaslundBh , @FraserGreenroyd  FYI - if you know of any existing panel comparer methods let me know.

### LINKED ISSUE #318: Robot_Toolkit: Openings pulling as loading panels
#### Description:

As well as being set as openings in panels, openings generate loading panels on pull. 

#### Expected behaviour:

Openings should not be pulled as loading panels.

### LINKED ISSUE #319: Robot_Toolkit: Openings not being pulled for cladding panels
#### Description:

Cladding panel openings not being pulled. 

#### Steps to reproduce:

Try and pull some cladding panels with openings in. 

#### Expected behaviour:

Openings should come through with the panels.

### LINKED ISSUE #321: Robot_Toolkit: Cladding panels property name hardcoded
#### Description:

The Create Panel method calls to set a cladding label based on the property name, and relies on the user inputting type-strong 'One-way X' names etc for the method to work. 

#### Steps to reproduce:

Try to push cladding panels with an incorrect name. 

#### Expected behaviour:

LoadingPanelProperty loading properties should be used to derive the name within the toolkit.

### LINKED ISSUE #322: Robot_Toolkit: Read cladding panels not setting the correct span directions
#### Description:

Reading cladding panels is not setting the correct span direction of the panel. 

#### Steps to reproduce:

Pull cladding panels.

### PR DESCRIPTION
**Pull request by rwemay**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #308 
 Closes #301 
 Closes #250 
 Closes #184 
 Closes #249 
 Closes #319 
 Closes #318 
 Closes #321 
 Closes #322 
 

 ### Test files

[Test files and models](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRobot%5FToolkit%2FIssues%2FRobot%5FToolkit%2DIssue308%2DUpdate%20Methods&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by rwemay** [comment]
@IsakNaslundBh , @kThorsager , @alelom  this is now getting there. I've fixed a few things related to panel update, specifically the support/releases for the edges, which were not properly implemented before. One thing to check before fully test/merge: 
 - I've added a call to Update methods for panel edge supports and releases - so if the label already exists in Robot, the properties of the label will be updated (supported/released directions). I'm not sure if this is the intention of the update methods - to update dependent properties, but if it is I think we need a different solution here. The way I've currently written, this will effectively be re-writing the same properties many times. 
 - Assuming we should be updating dependent properties, I need to implement something for other properties - e.g. panel thickness, if the name is the same. 
 - I'm not sure how the adapter is handling checking uniqueness of properties for similar named objects - so for example, if someone pushes lots of bars, with releases, and the releases have the same name, but different release directions, presumably all bars will have releases based on the first one pushed?

More questions than answers :) I'm off tomorrow, so catch up Thursday/later this week. Either way not one to rush through given extent of change necessary.

File: Robot_Adapter/CRUD/Update/Panels.cs [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+
+namespace BH.Adapter.Robot
+{
+    public partial class RobotAdapter
+    {
+        /***************************************************/
+        /****           Protected Methods               ****/
+        /***************************************************/
+
+        protected override bool UpdateOnly<T>(IEnumerable<T> panels, string tag = "", ActionConfig actionConfig = null)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/CRUD/Update/Panels.cs]: Would not override this method, but just change it do an Update method that then can be dynamically called by the IUpdate mehtod. (similar principle as what we do with the Create)

By overriding this method UpdateOnly will only work for panels, but no other objects.

File: Robot_Engine/Convert/ToRobot/Release.cs [hunk 2]
```diff
@@ -50,6 +50,21 @@ public static void RobotRelease(IRobotBarEndReleaseData rData, Constraint6DOF bh
 
         /***************************************************/
 
+        public static void RobotLinearRelease(IRobotLinearReleaseData rData, Constraint4DOF bhomRelease)
```
Comment (IsakNaslundBh) [inline Robot_Engine/Convert/ToRobot/Release.cs]: Think we will want to get all of these kinds of implicit comcall methods moved to the Adapter. Would not block the PR for that reason, as we generally have not followed this principle so far, but would aim to keep this in the Create method instead. WIll be significantly simpler to find as well.

Comment (rwemay) [reply Robot_Engine/Convert/ToRobot/Release.cs]: I might leave this for a later refactor... otherwise may be more confusion when moving parts of the code. Agree though, needs to go in the adapter - quite a bit of cleanup required! I'm not sure it should be kept in the create method as it's called by update too.

File: Robot_Adapter/CRUD/Update/Panels.cs (hunk 1 above)
Comment (rwemay) [reply Robot_Adapter/CRUD/Update/Panels.cs]: Sorry missed that one... was still getting to grips with new adapter. Updated now and reran just to check - all ok. Have you seen my comments in message above? Line 165 and 193 in this cs file are relevant. I'm not sure it's 'correct' to be calling update on properties of dependent objects, and if it is, I don't think this approach is sustainable (and will have a big performance hit as it scales).

**Comment by rwemay** [comment]
@IsakNaslundBh , I've tidied up this PR and network graph and I think/hope is ready for testing. Maybe one for us to talk/work though? Essentially final change is removing the auto-generated new properties when a named property (support/release) already exists, but returning a warning if we modify the named property in the model. Eventually I'd like to return 'one' warning to 'check push report' down the line - once we've built out the push report (returned as part of the 'success').

image

**Comment by rwemay** [comment]
Thanks @FraserGreenroyd , we were going to hold off the compliance updates for this/do it gradually. I see the tests are failing because we done a first pass (move cs files). Will see if I can try and add compliance changes too. 

@IsakNaslundBh  I've found another issue with the adapter update cycle, so have added do not merge label again... sorry. Hopefully will fix tomorrow.

File: Robot_Adapter/Convert/ToRobot/Geometry/Curve.cs [hunk 3]
```diff
@@ -20,29 +20,35 @@
...
+namespace BH.Adapter.Robot
 {
     public static partial class Convert
     {
         /***************************************************/
         /****           Public Methods                  ****/
         /***************************************************/
 
-        public static RobotGeoPoint3D FromBHoMGeometry(RobotApplication robotapp, Point point)
+        public static IRobotComponentType ToRobot(ICurve curve)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Geometry/Curve.cs]: Might tweak the name of this method, as it is checking if convert is possible, and if so to what, rather than doing the convert job.

File: Robot_Adapter/Convert/ToRobot/Loads/Load.cs [hunk 4]
```diff
@@ -28,15 +28,15 @@
...
+namespace BH.Adapter.Robot
 {
     public static partial class Convert
     {
         /***************************************************/
         /****           Public Methods                  ****/
         /***************************************************/
 
-        public static IRobotCaseNature RobotLoadNature(Loadcase lCase, out int subNature)
+        public static IRobotCaseNature ToRobot(Loadcase lCase, out int subNature)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Loads/Load.cs]: Maybe tweak name here as well, as it is not a full convert of the Loadcase. Alternatively, change the input to accept just a LoadNature and keep the name.

File: Robot_Adapter/Convert/ToRobot/Loads/Load.cs [hunk 5]
```diff
@@ -69,7 +69,7 @@ public static IRobotCaseNature RobotLoadNature(Loadcase lCase, out int subNature
 
         /***************************************************/
 
-        public static LoadNature BHoMLoadNature(IRobotCaseNature nature)
+        public static LoadNature FromRobot(IRobotCaseNature nature)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Loads/Load.cs]: This should be moved to a FromRobot file.

File: Robot_Adapter/Convert/ToRobot/Loads/Load.cs [hunk 6]
```diff
@@ -341,7 +336,7 @@ public static void RobotLoad(this oM.Structure.Loads.ContourLoad load, RobotSimp
 
         /***************************************************/
 
-        public static void RobotLoad(this oM.Structure.Loads.GeometricalLineLoad load, RobotSimpleCase sCase, RobotGroupServer rGroupServer)
+        public static void ToRobot(this oM.Structure.Loads.GeometricalLineLoad load, RobotSimpleCase sCase, RobotGroupServer rGroupServer)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Loads/Load.cs]: Would add a fall back method accepting `ILoad` at the end of this method, raising a warning that that load type is not supported yet.

File: Robot_Adapter/Convert/ToRobot/Properties/Material.cs [hunk 7]
```diff
@@ -57,7 +57,7 @@ public static void RobotMaterial(IRobotMaterialData materialData, IMaterialFragm
 
         /***************************************************/
 
-        public static IRobotMaterialType GetMaterialType(IMaterialFragment mat)
+        public static IRobotMaterialType ToRobot(IMaterialFragment mat)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Properties/Material.cs]: Would keep previous material name (or similar), as this is not full convert.

File: Robot_Adapter/Convert/ToRobot/Properties/MemberType.cs [hunk 8]
```diff
@@ -23,15 +23,15 @@
...
+namespace BH.Adapter.Robot
 {
     public static partial class Convert
     {
         /***************************************************/
         /****           Public Methods                  ****/
         /***************************************************/
 
-        public static void RobotMemberType(IRobotLabel robotMemberType, FramingElementDesignProperties framingElementDesignProperties)
+        public static void ToRobot(IRobotLabel robotMemberType, FramingElementDesignProperties framingElementDesignProperties)
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Convert/ToRobot/Properties/MemberType.cs]: Method not used. Can we remove? or saving for future usage?

File: Robot_Engine/Compare/Properties/Constraint4DOF.cs [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+namespace BH.Engine.Robot
+{
+    public class Constraint4DOFComparer : IEqualityComparer<Constraint4DOF>
+    {
+        /***************************************************/
+        /****           Public Methods                  ****/
+        /***************************************************/
+
+        public bool Equals(Constraint4DOF linearRelease1, Constraint4DOF linearRelease2)
+        {
```
Comment (IsakNaslundBh) [inline Robot_Engine/Compare/Properties/Constraint4DOF.cs]: small thing, but would add null checks etc at the start of this. Can check the start of the `NodeDistanceComparer`

File: Robot_Engine/Compare/Properties/Constraint6DOF.cs [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+namespace BH.Engine.Robot
+{
+    public class Constraint6DOFComparer : IEqualityComparer<Constraint6DOF>
+    {
+        /***************************************************/
+        /****           Public Methods                  ****/
+        /***************************************************/
+
+        public bool Equals(Constraint6DOF support_1, Constraint6DOF support_2)
+        {
```
Comment (IsakNaslundBh) [inline Robot_Engine/Compare/Properties/Constraint6DOF.cs]: small thing, but would add null checks etc at the start of this. Can check the start of the `NodeDistanceComparer`

File: Robot_Engine/Compare/Properties/LoadingPanelProperty.cs [hunk 11]
```diff
@@ -21,43 +21,41 @@
...
-            stiffness.Add(suppData.KX);
-            stiffness.Add(suppData.KY);
-            stiffness.Add(suppData.KZ);
-            stiffness.Add(suppData.HX);
-            stiffness.Add(suppData.HY);
-            stiffness.Add(suppData.HZ);
-
-            Constraint6DOF const6DOF = BH.Engine.Structure.Create.Constraint6DOF(robSupport.Name, fixity, stiffness);
-            return const6DOF;
+            if (property1.Name == property2.Name &&
```
Comment (IsakNaslundBh) [inline Robot_Engine/Compare/Properties/LoadingPanelProperty.cs]: small thing, but would add null checks etc at the start of this. Can check the start of the `NodeDistanceComparer`

File: Robot_Adapter/Types/Comparer.cs [hunk 12]
```diff
@@ -47,6 +48,7 @@ protected void SetupComparers()
                 {typeof(Bar), new BarEndNodesDistanceComparer(3) },
                 {typeof(ISectionProperty), new BHoMObjectNameOrToStringComparer() },
                 {typeof(Material), new BHoMObjectNameComparer() },
```
Comment (IsakNaslundBh) [inline Robot_Adapter/Types/Comparer.cs]: ohhh, wonder how this did not get picked up before!
Would get rid of the Material one here, as physical/common materials are not supported.

File: Robot_Adapter/CRUD/Update/IUpdate.cs [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+            success = Update(objects as dynamic);
+            updateview();
+            return success;
+        }
+
+        /***************************************************/
+
+        protected bool Update(IEnumerable<IBHoMObject> bhomObjects)
+        {
+            return true;
```
[the remark this answers is not in the document]
Comment (rwemay) [reply Robot_Adapter/CRUD/Update/IUpdate.cs]: Good idea. How about `"Objects of type '" + bhomObjects.First().GetType().ToString() + "' not updated"`

[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Robot_Adapter/CRUD/Update/IUpdate.cs]: Something like that would work I think. Might tweak it slightly (to avoid crashes for empty collections) to:

```
IBHoMObject first = bhomObjects.FirstOrDefault();

if(first != null)
{
    Engine.Reflection.Compute.RecordWarning("Objects to type " + first.GetType().Name + " can currently not be updated");
}

```

WIll let you choose the exact wording, but good to use FirstORDefault followed by a null check! :)

File: Robot_Adapter/Convert/ToRobot/Properties/MemberType.cs (hunk 8 above)
Comment (rwemay) [reply Robot_Adapter/Convert/ToRobot/Properties/MemberType.cs]: Would prefer to keep for now, took a bit of effort to get those params from memory.

Comment (IsakNaslundBh) [reply Robot_Adapter/Convert/ToRobot/Properties/MemberType.cs]: ok, sure, lets keep!

File: Robot_Adapter/CRUD/Update/Elements/Panels.cs [hunk 14]
```diff
@@ -0,0 +1,88 @@
...
+
+        protected bool Update(IEnumerable<Panel> panels)
+        {
+            Dictionary<int, HashSet<string>> panelTags = GetTypeTags(typeof(Panel));
+            RobotObjObjectServer robotObjectServer = m_RobotApplication.Project.Structure.Objects;
+            foreach (Panel panel in panels)
+            {
+                RobotObjObject robotPanel = robotObjectServer.Get((int)panel.CustomData[AdapterIdName]) as RobotObjObject;
+                if (robotPanel == null)
+                    return false;
```
Comment (IsakNaslundBh) [inline Robot_Adapter/CRUD/Update/Elements/Panels.cs]: Might tweak the beginning part here, down to the rotpanel == null check to something like:

```
                if (panel == null)
                {
                    Engine.Reflection.Compute.RecordWarning("At least one provided panel is null and is not updated!");
                    continue;
                }

                if (!panel.CustomData.ContainsKey(AdapterIdName))
                {
                    string panelName = string.IsNullOrWhiteSpace(panel.Name) ? "no name" : "name " + panel.Name;
                    Engine.Reflection.Compute.RecordWarning("Panel with " + panelName + " did not contain any Robot id. To update panels they need this information. For this operation to work, try using a Panel that has first been pulled from Robot");
                    continue;
                }

                RobotObjObject robotPanel = robotObjectServer.Get((int)panel.CustomData[AdapterIdName]) as RobotObjObject;
                if (robotPanel == null)
                {
                    Engine.Reflection.Compute.RecordWarning("Could not find a panel with the Id " + panel.CustomData[AdapterIdName].ToString() + " in Robot. Panel could not be updated!");
                    continue;
                }
```
